# Site settings
title: Rees Electrical
email: simon.rees@btconnect.com
phone_number: 07960890484
description: "Rees Electrical Providing Electrical Installation to Pembrokeshire (Electrician Service)"
baseurl: "http://www.reeselectrical.com"
url: "http://www.reeselectrical.com"
port: 4444

# Build settings
markdown: kramdown