# Site settings
title: Rees Electrical
email: nicholas.rees@live.co.uk
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "http://www.reeselectrical.com"
url: "http://www.reeselectrical.com"

twitter_username: nprees
github_username: nprees

# Build settings
markdown: kramdown
